# Site settings
title: Omniverse Tutorials
description: A collection of tutorials for Nvidia Omniverse, including guides on setting up your environment, building UIs, and creating extensions.
baseurl: "" # The subpath of your site, e.g., /blog
url: "https://thomas-quantyverse.github.io" # The base hostname & protocol for your site

# Author information
author: 
  name: "Thomas Bernhard"
  email: "thomas@quantyverse.com"

# Theme configuration
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme # make sure you have this plugin enabled
  - jekyll-feed
  - jekyll-seo-tag

# Navigation Bar
navigation:
  - title: "Home"
    url: "/"
  - title: "Basics"
    url: "/basics/"
  - title: "User Interface (UI)"
    url: "/ui/"
  - title: "Examples"
    url: "/examples/"
  - title: "Setting Up Environment"
    url: "/basics/setting-up-environment/"

# Defaults for layout, content, etc.
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "Your Name"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minimal-mistakes-jekyll

# Additional configurations
paginate: 5 # Number of posts per page in paginated navigation
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .jekyll-cache/
  - .jekyll-metadata